# Generated by Django 4.2.3 on 2023-08-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_city_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='nnnimage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
