# Generated by Django 4.2.3 on 2023-07-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='evname',
            new_name='evename',
        ),
        migrations.AddField(
            model_name='event',
            name='evedescription',
            field=models.TextField(default=1, verbose_name='الوصف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='evepicture',
            field=models.ImageField(default=1, upload_to='imag', verbose_name='صورة المناسبة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='evevenue',
            field=models.CharField(choices=[('مطعم1', 'مطعم1'), ('مطعم2', 'مطعم2')], default=1, max_length=50, verbose_name='المكان'),
            preserve_default=False,
        ),
    ]
