# Generated by Django 4.2.3 on 2023-07-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_evname_event_evename_event_evedescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='evedescription',
            new_name='eve_description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='evename',
            new_name='eve_name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='evevenue',
            new_name='eve_venue',
        ),
        migrations.RemoveField(
            model_name='event',
            name='evepicture',
        ),
        migrations.AddField(
            model_name='event',
            name='eve_picture',
            field=models.ImageField(default='ee', upload_to='imag', verbose_name='صورة المناسبة'),
        ),
        migrations.AddField(
            model_name='event',
            name='eve_published_at',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='event',
            name='eve_user_add',
            field=models.CharField(default='kinan', max_length=50, verbose_name=''),
            preserve_default=False,
        ),
    ]
