# Generated by Django 4.2.3 on 2023-07-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_event_eve_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eve_user_add',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='eve_venue',
            field=models.CharField(choices=[('مطعم1', 'مطعم'), ('مطعم2', 'بار')], max_length=50, verbose_name='المكان'),
        ),
    ]
