# Generated by Django 4.2.3 on 2023-07-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_eve_user_add_alter_event_eve_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eve_image',
            field=models.ImageField(default=1, upload_to='event/', verbose_name='صورة المناسبة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='eve_venue',
            field=models.CharField(choices=[('مطعم', 'مطعم'), ('بار', 'بار')], max_length=50, verbose_name='المكان'),
        ),
    ]
