# Generated by Django 4.2.3 on 2023-07-27 20:49

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_eve_image_alter_event_eve_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eve_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='user name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eve_image',
            field=models.ImageField(upload_to=event.models.image_upload, verbose_name='صورة المناسبة'),
        ),
    ]
