# Generated by Django 4.2.3 on 2023-07-28 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_catagory_alter_event_eve_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eve_catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.catagory', verbose_name='Catagory'),
            preserve_default=False,
        ),
    ]
