# Generated by Django 4.2.3 on 2023-07-28 00:22

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_event_eve_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eve_date_start',
            field=models.DateField(null=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eve_image',
            field=models.ImageField(upload_to=event.models.image_upload, verbose_name='Event Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eve_time_start',
            field=models.TimeField(null=True, verbose_name='Evevent Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eve_venue',
            field=models.CharField(choices=[('مطعم', 'مطعم'), ('بار', 'بار')], max_length=50, verbose_name='venue'),
        ),
    ]
