# Generated by Django 4.2.3 on 2023-07-29 00:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_event_eve_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='EventCatagory',
        ),
        migrations.AlterField(
            model_name='event',
            name='eve_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('family', 'Family Events'), ('couple', 'For Couples'), ('women', 'For Women Only'), ('men', 'For Men Only'), ('public', 'Public Events'), ('children', 'For Children')], max_length=50, verbose_name='Event Type'),
        ),
    ]
