# Generated by Django 4.2.3 on 2023-07-29 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_rename_catagory_eventcatagory_alter_event_eve_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=50, verbose_name='Name')),
                ('res_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('res_phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('res_people', models.IntegerField(verbose_name='People')),
                ('res_date', models.DateField(verbose_name='Date')),
                ('res_time', models.TimeField(verbose_name='Time')),
                ('res_Notes', models.TextField(verbose_name='Notes')),
                ('res_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='Event')),
            ],
        ),
    ]
