# Generated by Django 4.2.3 on 2023-07-29 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='res_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='res_time',
        ),
    ]
