# Generated by Django 4.2.3 on 2023-07-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_remove_reservation_res_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcatagory',
            options={'verbose_name': 'Catagory', 'verbose_name_plural': 'Categories'},
        ),
    ]
