# Generated by Django 4.2.3 on 2023-07-31 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_alter_eventcatagory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eve_user_add',
        ),
    ]
