# Generated by Django 4.2.3 on 2023-07-31 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_event_eve_user_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eve_user_add',
            new_name='eve_owner',
        ),
    ]
