# Generated by Django 4.2.3 on 2023-08-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_rename_eve_user_add_event_eve_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eve_date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eve_time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Evevent Time'),
        ),
    ]
