# Generated by Django 4.2.3 on 2023-08-01 14:12

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_alter_event_eve_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eve_image',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.image_upload, verbose_name='Event Image'),
        ),
    ]
