# Generated by Django 4.2.3 on 2023-08-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_alter_event_eve_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eve_datetime_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event Date and Time'),
        ),
    ]
