# Generated by Django 4.2.3 on 2023-08-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_event_eve_datetime_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eve_datetime_start',
        ),
    ]
