# Generated by Django 4.2.3 on 2023-07-29 00:39

from django.db import migrations, models
import django.db.models.deletion
import venue.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VenueCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_ve_name', models.CharField(max_length=50, verbose_name='Venue Catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ve_name', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('ve_description', models.TextField(verbose_name='Venue Description')),
                ('ve_address', models.CharField(max_length=300)),
                ('ve_phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('ve_email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('ve_zip_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='Zip/Post Code')),
                ('ve_web', models.URLField(blank=True, null=True, verbose_name='Website Address')),
                ('ve_slug', models.SlugField(blank=True, null=True)),
                ('ve_image', models.ImageField(upload_to=venue.models.image_upload, verbose_name='Venue Image')),
                ('ve_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venuecatagory', verbose_name='Catagory')),
            ],
        ),
    ]
