# Generated by Django 4.2.3 on 2023-07-29 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venuecatagory',
            options={'verbose_name': 'Catagory', 'verbose_name_plural': 'Categories'},
        ),
    ]
