# Generated by Django 4.2.3 on 2023-07-29 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_venue_ve_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='ve_star',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Venue Star'),
        ),
    ]
