# Generated by Django 4.2.3 on 2023-07-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_alter_venue_ve_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='ve_star',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Venue Star'),
        ),
    ]
