# Generated by Django 4.2.3 on 2023-07-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_alter_venue_ve_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='ve_address',
            field=models.CharField(max_length=300, verbose_name='Venue Address'),
        ),
    ]
